Improve linting with additional job that validates changie entry exists when it should be included. Certain exclusions are added such as labels for `dependencies` by Renovate, and `no-changie-required` label for exceptions. This will use PR comment type so automatic changes required will show up.

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -23,10 +23,10 @@ jobs:
       contents: read # For repo checkout
     steps:
       - name: checkout
-        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
+        uses: actions/checkout@v4
       - name: set-aqua-policy-if-file-exists
         run: |
-          if [ -f aqua-policy.yaml ]; then
+          if [[ -f aqua-policy.yaml ]]; then
             echo "AQUA_POLICY_CONFIG=${GITHUB_WORKSPACE}/aqua-policy.yaml:${AQUA_POLICY_CONFIG}" >> $GITHUB_ENV
           else
             echo "👉 No aqua-policy.yaml file found, skipping setting AQUA_POLICY_CONFIG"
@@ -44,3 +44,93 @@ jobs:
         uses: trunk-io/trunk-action@86b68ffae610a05105e90b1f52ad8c549ef482c2 # v1.1.16
         with:
           arguments: --github-annotate-new-only=true
+
+  changie-validation:
+    name: changie-validation
+    runs-on: ubuntu-latest
+    permissions:
+      pull-requests: write
+      contents: read
+      checks: write
+    env:
+      GH_TOKEN: ${{ github.token }}
+      GITHUB_REF_BRANCH: ${{ github.ref }}
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: ${{ env.GITHUB_REF_BRANCH }}
+
+      - name: Set up default branch name
+        id: default_branch
+        run: echo "DEFAULT_BRANCH=$(gh repo view --json defaultBranchRef -q '.defaultBranchRef.name')" >> $GITHUB_ENV
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Check for .changes directory
+        id: check_changes_dir
+        run: |
+          if [[ -d ".changes" ]]; then
+            echo "changes_dir_exists=true" >> $GITHUB_OUTPUT
+          else
+            echo "changes_dir_exists=false" >> $GITHUB_OUTPUT
+            echo "⏩ no changie entry required on this"
+          fi
+
+      - name: Fetch default branch
+        id: fetch_branches
+        run: |
+          git fetch origin ${{ env.DEFAULT_BRANCH }}
+          git fetch origin ${{ env.GITHUB_REF_BRANCH }}
+
+      - name: Check for labels
+        id: check_labels
+        run: |
+          echo "no_changie_required=false" >> $GITHUB_OUTPUT
+          echo "dependencies=false" >> $GITHUB_OUTPUT
+          for label in $(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name'); do
+            if [[ "$label" == "no-changie-required" ]]; then
+              echo "no_changie_required=true" >> $GITHUB_OUTPUT
+              echo "❎ bypass on changie noted due to label"
+            elif [[ "$label" == "dependencies" ]]; then
+              echo "dependencies=true" >> $GITHUB_OUTPUT
+            fi
+          done
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Validate changie entry
+        id: validate_changie_entry
+        if: steps.check_changes_dir.outputs.changes_dir_exists == 'true' && steps.check_labels.outputs.no_changie_required == 'false' && steps.check_labels.outputs.dependencies == 'false'
+        run: |
+          # Fetch existing comments
+          existing_comments=$(gh pr view ${{ github.event.pull_request.number }} --json comments --jq '.comments[].body')
+
+          changes=$(git diff --name-only origin/${{ env.DEFAULT_BRANCH }}...HEAD -- .changes/)
+
+          if [[ -n "$changes" ]]; then
+            echo "Changie entry found"
+            comment="✅ changie entry was found"
+            if ! echo "$existing_comments" | grep -q "✅ changie entry was found"; then
+              gh pr review ${{ github.event.pull_request.number }} --approve
+              gh pr comment ${{ github.event.pull_request.number }} --body "$comment"
+            fi
+          else
+            echo "No changie entry found in .changes"
+            comment="❌ A changie entry is required in .changes/"
+            if ! echo "$existing_comments" | grep -q "❌ A changie entry is required in .changes/unreleased"; then
+              echo "adding review comment saying required, since not seeing prior comment before"
+              gh pr review ${{ github.event.pull_request.number }} --request-changes --body "$comment"
+            fi
+          fi
+
+          # Update or post the review comment
+          if [[ -n "$comment" ]]; then
+            if echo "$existing_comments" | grep -q "$comment"; then
+              echo "Review comment already posted"
+            else
+              echo "adding review comment since not seeing prior comment before"
+              gh pr comment ${{ github.event.pull_request.number }} --body "$comment"
+            fi
+          fi
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
